#!/bin/sh

CMD_TYPE=$1
URL=$2
OUTPUT_FILE=$3

if [ x"$CMD_TYPE" = "xmsoffice" ] ; then
  TARGET_FILE=`echo $URL | sed -e "s#^file:/*#/#g"`
  TMP_FILE=/tmp/thumbnail.$$.pdf
  unoconv -o $TMP_FILE -f pdf $TARGET_FILE
  convert -thumbnail 160x120! $TMP_FILE $OUTPUT_FILE
  rm $TMP_FILE
else
  echo "Unsupported type: $CMD_TYPE"
  exit 1
fi

