<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%--
 --%><%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%><%--
 --%><%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %><%--
 --%><%@taglib prefix="html" uri="http://struts.codelibs.org/tags-html"%><%--
 --%><%@taglib prefix="bean" uri="http://struts.apache.org/tags-bean"%><%--
 --%><%@taglib prefix="logic" uri="http://struts.apache.org/tags-logic" %><%--
 --%><%@taglib prefix="tiles" uri="http://jakarta.apache.org/struts/tags-tiles"%><%--
 --%><%@taglib prefix="s" uri="http://sastruts.seasar.org" %><%--
 --%><%@taglib prefix="f" uri="http://sastruts.seasar.org/functions" %><%--
 --%><%@taglib prefix="m" uri="http://taglibs.mobylet.org/" %><%--
 --%><%@taglib prefix="fe" uri="http://fess.codelibs.org/functions" %><%--
 --%><c:set var="contextPath" value="${request.contextPath}"/>