/*
 * Copyright 2012-2025 CodeLibs Project and the Others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.codelibs.fess.api.v2.handlers;

import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Pattern;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codelibs.core.lang.StringUtil;
import org.codelibs.fess.api.v2.V2ErrorCode;
import org.codelibs.fess.mylasta.direction.FessConfig;
import org.codelibs.fess.util.ComponentUtil;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Handles {@code DELETE /api/v2/chat/sessions/{session_id}} — clears the
 * conversation history for a specific chat session.
 *
 * <p>This endpoint replaces the {@code clear: true} flag that was previously
 * accepted by {@code POST /api/v2/chat}. Separating the clear operation into a
 * dedicated DELETE endpoint follows REST conventions and allows the POST handler
 * to be a pure chat-message endpoint without state-mutation side-effects.</p>
 *
 * <p>Success response shape:</p>
 * <pre>{@code
 * { "response": { "status": 0, "session_id": "...", "cleared": true } }
 * }</pre>
 *
 * <p>Error responses follow the standard v2 envelope:</p>
 * <ul>
 *   <li>{@code 405} — wrong HTTP method</li>
 *   <li>{@code 400} — invalid or missing session_id (fails URL pattern validation)</li>
 *   <li>{@code 404} — session not found or belongs to a different user</li>
 *   <li>{@code 429} — rate limit exceeded</li>
 *   <li>{@code 500} — unexpected server error</li>
 * </ul>
 *
 * <p>Authentication posture: the same as {@link ChatHandler} — anonymous users are
 * identified by the cookie-bound userCode; the session_id ownership check in
 * {@code ChatSessionManager#clearSession} prevents cross-user clearing.</p>
 */
public class ChatSessionClearHandler {

    private static final Logger logger = LogManager.getLogger(ChatSessionClearHandler.class);

    /**
     * Default constructor. The handler is stateless and intended to be
     * instantiated once by the API manager and shared across concurrent requests.
     */
    public ChatSessionClearHandler() {
        // no-op
    }

    /**
     * Allowed characters in a session_id URL path segment.
     * Accepts alphanumerics, hyphens, underscores, and dots — the same character
     * set generated by UUID-style identifiers and common session ID conventions.
     * The length cap of 128 prevents excessively large values from reaching the backend.
     */
    private static final Pattern SESSION_ID_PATTERN = Pattern.compile("^[A-Za-z0-9._\\-]{1,128}$");

    /**
     * Handles a DELETE request for {@code /api/v2/chat/sessions/{session_id}}.
     *
     * @param req       the incoming HTTP request
     * @param res       the HTTP response to write to
     * @param sessionId the session ID extracted from the URL path by the router
     * @throws IOException if writing the response fails
     */
    public void handle(final HttpServletRequest req, final HttpServletResponse res, final String sessionId) throws IOException {
        if (!"DELETE".equalsIgnoreCase(req.getMethod())) {
            res.setHeader("Allow", "DELETE");
            ComponentUtil.getV2EnvelopeWriter().writeError(res, V2ErrorCode.METHOD_NOT_ALLOWED, "method not allowed");
            return;
        }

        final FessConfig fessConfig = ComponentUtil.getFessConfig();
        if (!fessConfig.isRagChatEnabled()) {
            ComponentUtil.getV2EnvelopeWriter().writeError(res, V2ErrorCode.INVALID_REQUEST, "chat is not enabled");
            return;
        }

        // Validate the session_id path segment before touching any backend state.
        if (sessionId == null || !SESSION_ID_PATTERN.matcher(sessionId).matches()) {
            ComponentUtil.getV2EnvelopeWriter().writeError(res, V2ErrorCode.INVALID_REQUEST, "invalid session_id");
            return;
        }

        final String userId = getUserId(req);

        // Apply the same rate-limit as POST /api/v2/chat — clearing a session still
        // touches backend state and should be subject to abuse protection.
        final LoginRateLimiter limiter;
        try {
            limiter = ComponentUtil.getLoginRateLimiter();
        } catch (final RuntimeException e) {
            logger.warn("[RAG] /api/v2/chat/sessions DELETE rate-limit lookup failed", e);
            ComponentUtil.getV2EnvelopeWriter().writeError(res, V2ErrorCode.INTERNAL_ERROR, "internal error");
            return;
        }
        final int chatLimit = fessConfig.getChatRateLimitPerMinute();
        // Skip the per-user throttle for anonymous callers with no resolvable user id
        // (e.g. a guest whose session is not yet established): a null/blank key would
        // otherwise hit the limiter's null-key deny path and 429 the first request.
        if (limiter != null && chatLimit > 0 && StringUtil.isNotBlank(userId)
                && !limiter.allow(LoginRateLimiter.Scope.CHAT, userId, chatLimit, 60)) {
            res.setHeader("Retry-After", "60");
            ComponentUtil.getV2EnvelopeWriter().writeError(res, V2ErrorCode.RATE_LIMITED, "too many chat requests");
            return;
        }

        try {
            final boolean cleared = ComponentUtil.getChatSessionManager().clearSession(sessionId, userId);
            if (!cleared) {
                ComponentUtil.getV2EnvelopeWriter().writeError(res, V2ErrorCode.NOT_FOUND, "session not found");
                return;
            }
            final Map<String, Object> payload = new LinkedHashMap<>();
            payload.put("session_id", sessionId);
            payload.put("cleared", true);
            ComponentUtil.getV2EnvelopeWriter().writeSuccess(res, payload);
        } catch (final Exception e) {
            logger.warn("[RAG] DELETE /api/v2/chat/sessions/{} failed. error={}", sessionId, e.getMessage(), e);
            ComponentUtil.getV2EnvelopeWriter().writeError(res, V2ErrorCode.INTERNAL_ERROR, "internal error");
        }
    }

    /**
     * Resolves the effective chat user id. Exposed as a seam so unit tests can override the user
     * identity directly. {@code SystemHelper}/{@code UserInfoHelper} are smart-deploy components,
     * so stubbing them via {@code ComponentUtil.register} is not reliable once the shared test
     * container has resolved the real ones; overriding this method avoids that fragility.
     *
     * @param req the incoming HTTP request
     * @return the user identifier (never null)
     */
    protected String getUserId(final HttpServletRequest req) {
        return ComponentUtil.getChatApiHelper().getUserId();
    }
}
